#!/bin/sh

DAEMON="/usr/local/bin/yandex-disk"
LOGGER="/var/packages/YandexDisk/scripts/yandex-logger"
CLEANER="/var/packages/YandexDisk/scripts/yandex-cleaner"

case "$1" in
    start)
		$DAEMON start
		$LOGGER &
		$CLEANER &
		exit 0
        ;;
    stop)
		$DAEMON stop
		pkill -f yandex-logger
		pkill -f yandex-cleaner
		exit 0
        ;;
    status)
		ps -eo cmd | grep -q "[y]andex-disk" && exit 0 || exit 3
		;;
esac
