#!/bin/bash

ps -eo pid,cmd | grep "[y]andex-cleaner" | grep -v $$ > /dev/null && exit 1

CONFIG_FILE="/var/packages/YandexDisk/home/.config/yandex-disk/config.cfg"
CLEAN_INTERVAL=3600

while true; do
    TARGET_DIR=$(grep -Ei '^dir=' "$CONFIG_FILE" | cut -d'=' -f2- | tr -d '"')

    if [ -n "$TARGET_DIR" ]; then
        find "$TARGET_DIR" -type d -name "@eaDir" -prune -exec rm -rf {} +
        find "$TARGET_DIR" -type f -name "Thumbs.db" -delete
    fi

    sleep "$CLEAN_INTERVAL"
done
